services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  balanceapi:
    build:
      context: ./BalanceApi
      dockerfile: BalanceApi/Dockerfile
    image: balanceapi:latest
    environment:
      ASPNETCORE_URLS: http://+:8082
      ASPNETCORE_ENVIRONMENT: Development
      Mongo__ConnectionString: mongodb://mongo:27017/?connectTimeoutMS=60000&serverSelectionTimeoutMS=60000
      Mongo__DatabaseName: balances_db
    ports:
      - "8082:8082"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  paymentapi:
    build:
      context: ./PaymentApi
      dockerfile: PaymentApi/Dockerfile
    image: paymentapi:latest
    environment:
      ASPNETCORE_URLS: http://+:8080
      Rabbit__HostName: rabbitmq
      Rabbit__UserName: admin
      Rabbit__Password: admin
      Rabbit__QueueName: payment-process-topic
      Mongo__ConnectionString: mongodb://mongo:27017/?connectTimeoutMS=60000&serverSelectionTimeoutMS=60000
      Mongo__DatabaseName: payments_db
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  paymentworker:
    build:
      context: ./PaymentWorker
      dockerfile: PaymentWorker/Dockerfile
    image: paymentworker:latest
    environment:
      Rabbit__HostName: rabbitmq
      Rabbit__UserName: admin
      Rabbit__Password: admin
      Rabbit__QueueName: payment-process-topic
      BalanceApi__BaseAddress: http://balanceapi:8082
      Mongo__ConnectionString: mongodb://mongo:27017/?connectTimeoutMS=60000&serverSelectionTimeoutMS=60000
      Mongo__DatabaseName: payments_db
    depends_on:
      rabbitmq:
        condition: service_healthy
      balanceapi:
        condition: service_started
      mongo:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge